'use client';

import { useState, useCallback } from 'react';
import { useRouter } from 'next/navigation';
import {
  Plus, Trash2, Wand2, ChevronUp, ChevronDown, Search,
  Eye, CheckCircle2, AlertTriangle, XCircle, ChevronRight,
  GripVertical, X,
} from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter,
} from '@/components/ui/dialog';
import {
  Select, SelectContent, SelectItem, SelectTrigger, SelectValue,
} from '@/components/ui/select';
import { mockQuestions, type Question, type QuestionType, type Difficulty } from '@/mock/data';
import { toast } from 'sonner';

// ── types ──────────────────────────────────────────────────────────────────
interface SectionQuestion { qId: string; score: number; }
interface Section {
  id: string;
  name: string;
  targetScore: number;
  collapsed: boolean;
  questions: SectionQuestion[];
}
interface PaperMeta {
  title: string;
  duration: number;
  targetScore: number;
  instructions: string;
}
interface DiffDist { easy: number; medium: number; hard: number; }
interface AutoTypeConfig { count: number; scoreEach: number; diff: DiffDist; }

// ── constants ──────────────────────────────────────────────────────────────
const typeLabels: Record<QuestionType, string> = {
  choice: '单选题', fill: '填空题', short: '简答题', essay: '论述题',
  tf: '判断题', attachment: '附件题',
};
const diffLabels: Record<Difficulty, string> = { easy: '简单', medium: '中等', hard: '困难' };
const diffColors: Record<Difficulty, string> = {
  easy: 'bg-green-100 text-green-700',
  medium: 'bg-yellow-100 text-yellow-700',
  hard: 'bg-red-100 text-red-700',
};
const DURATIONS = [60, 90, 120, 150, 180];
const CHINESE_NUM = ['一', '二', '三', '四', '五', '六', '七', '八'];

const DEFAULT_SECTIONS: Section[] = [
  { id: 's1', name: '选择题', targetScore: 30, collapsed: false, questions: [] },
  { id: 's5', name: '判断题', targetScore: 10, collapsed: false, questions: [] },
  { id: 's2', name: '填空题', targetScore: 20, collapsed: false, questions: [] },
  { id: 's3', name: '简答题', targetScore: 20, collapsed: false, questions: [] },
  { id: 's4', name: '论述题', targetScore: 20, collapsed: false, questions: [] },
];

const TYPE_SECTION_MAP: Record<QuestionType, string> = {
  choice: 's1', tf: 's5', fill: 's2', short: 's3', essay: 's4', attachment: 's4',
};

function mkId() { return Math.random().toString(36).slice(2, 8); }
const shuffled = <T,>(a: T[]) => [...a].sort(() => Math.random() - 0.5);

// ── main ───────────────────────────────────────────────────────────────────
export default function CreateExamPage() {
  const router = useRouter();
  const [activeTab, setActiveTab] = useState<'manual' | 'auto'>('manual');
  const [autoGeneratedBanner, setAutoGeneratedBanner] = useState(false);

  // paper meta
  const [meta, setMeta] = useState<PaperMeta>({
    title: '', duration: 120, targetScore: 100, instructions: '',
  });

  // manual: left panel filters
  const [subjectFilter, setSubjectFilter] = useState('all');
  const [diffFilter, setDiffFilter] = useState('all');
  const [typeFilter, setTypeFilter] = useState('all');
  const [searchText, setSearchText] = useState('');

  // manual: right panel sections
  const [sections, setSections] = useState<Section[]>(DEFAULT_SECTIONS);
  const [editSectionScore, setEditSectionScore] = useState<{ id: string; val: string } | null>(null);
  const [addSectionOpen, setAddSectionOpen] = useState(false);
  const [newSectionName, setNewSectionName] = useState('');
  const [newSectionScore, setNewSectionScore] = useState(10);
  const [deleteSectionTarget, setDeleteSectionTarget] = useState<Section | null>(null);
  const [inlineScoreEdit, setInlineScoreEdit] = useState<{ sid: string; qid: string; val: string } | null>(null);
  const [dragItem, setDragItem] = useState<{ sid: string; qi: number } | null>(null);
  const [dragOver, setDragOver] = useState<{ sid: string; qi: number } | null>(null);

  // preview
  const [previewOpen, setPreviewOpen] = useState(false);

  // auto config
  const [autoConfig, setAutoConfig] = useState({
    subject: '数据结构',
    totalScore: 100,
    duration: 120,
    excludeRecent: false,
    sameChapterMax: 3,
  });
  const [autoTypes, setAutoTypes] = useState<Record<QuestionType, AutoTypeConfig>>({
    choice:     { count: 10, scoreEach: 4, diff: { easy: 30, medium: 50, hard: 20 } },
    tf:         { count: 5,  scoreEach: 2, diff: { easy: 50, medium: 50, hard: 0  } },
    fill:       { count: 5,  scoreEach: 4, diff: { easy: 40, medium: 40, hard: 20 } },
    short:      { count: 2,  scoreEach: 10, diff: { easy: 30, medium: 50, hard: 20 } },
    essay:      { count: 1,  scoreEach: 20, diff: { easy: 0,  medium: 50, hard: 50 } },
    attachment: { count: 0,  scoreEach: 15, diff: { easy: 0,  medium: 100, hard: 0 } },
  });
  const [diffExpandFor, setDiffExpandFor] = useState<QuestionType | null>(null);

  // ── computed ──
  const pool = mockQuestions;
  const subjects = [...new Set(pool.map((q) => q.subject))];

  const filteredPool = pool.filter((q) => {
    const ms = subjectFilter === 'all' || q.subject === subjectFilter;
    const md = diffFilter === 'all' || q.difficulty === diffFilter;
    const mt = typeFilter === 'all' || q.type === typeFilter;
    const mq = !searchText || q.content.toLowerCase().includes(searchText.toLowerCase());
    return ms && md && mt && mq;
  });

  const allSectionQIds = sections.flatMap((s) => s.questions.map((q) => q.qId));
  const totalQuestions = allSectionQIds.length;
  const currentScore = sections.reduce(
    (sum, s) => sum + s.questions.reduce((ss, sq) => ss + sq.score, 0), 0
  );
  const scoreDiff = currentScore - meta.targetScore;

  // auto library check
  const autoLibCheck = useCallback((type: QuestionType) => {
    const cfg = autoTypes[type];
    const available = pool.filter((q) => q.type === type && (autoConfig.subject === 'all' || q.subject === autoConfig.subject)).length;
    const need = cfg.count;
    if (available >= need * 1.5) return 'ok';
    if (available >= need) return 'warn';
    return 'error';
  }, [autoTypes, autoConfig.subject, pool]);

  const autoTotalScore = (Object.keys(autoTypes) as QuestionType[]).reduce(
    (s, t) => s + autoTypes[t].count * autoTypes[t].scoreEach, 0
  );
  const canGenerate = (Object.keys(autoTypes) as QuestionType[]).every(
    (t) => autoTypes[t].count === 0 || autoLibCheck(t) !== 'error'
  );

  // ── section helpers ──
  const getQById = (id: string) => pool.find((q) => q.id === id);

  const addToSection = (q: Question, sid?: string) => {
    const targetSid = sid ?? TYPE_SECTION_MAP[q.type] ?? sections[0]?.id;
    if (!targetSid) return;
    setSections((prev) => prev.map((s) =>
      s.id !== targetSid ? s :
      s.questions.some((sq) => sq.qId === q.id) ? s :
      { ...s, questions: [...s.questions, { qId: q.id, score: q.score }] }
    ));
  };

  const removeFromSection = (sid: string, qid: string) => {
    setSections((prev) => prev.map((s) =>
      s.id !== sid ? s : { ...s, questions: s.questions.filter((sq) => sq.qId !== qid) }
    ));
  };

const updateQuestionScore = (sid: string, qid: string, score: number) => {
    setSections((prev) => prev.map((s) =>
      s.id !== sid ? s : { ...s, questions: s.questions.map((sq) => sq.qId === qid ? { ...sq, score } : sq) }
    ));
  };

  const toggleCollapse = (sid: string) => {
    setSections((prev) => prev.map((s) => s.id === sid ? { ...s, collapsed: !s.collapsed } : s));
  };

  const confirmDeleteSection = (s: Section) => {
    setSections((prev) => prev.filter((x) => x.id !== s.id));
    setDeleteSectionTarget(null);
    toast.success('大题已删除');
  };

  const addSection = () => {
    if (!newSectionName.trim()) { toast.error('请输入大题名称'); return; }
    setSections((prev) => [...prev, {
      id: mkId(), name: newSectionName.trim(),
      targetScore: newSectionScore, collapsed: false, questions: [],
    }]);
    setNewSectionName(''); setNewSectionScore(10); setAddSectionOpen(false);
    toast.success('大题已添加');
  };

  // ── auto generate ──
  const handleGenerate = () => {
    const newSections: Section[] = (Object.entries(autoTypes) as [QuestionType, AutoTypeConfig][])
      .filter(([, cfg]) => cfg.count > 0)
      .map(([type, cfg], i) => {
        const available = pool.filter((q) => q.type === type && (autoConfig.subject === 'all' || q.subject === autoConfig.subject));
        const picked = shuffled(available).slice(0, cfg.count);
        return {
          id: mkId(),
          name: typeLabels[type],
          targetScore: cfg.count * cfg.scoreEach,
          collapsed: false,
          questions: picked.map((q) => ({ qId: q.id, score: cfg.scoreEach })),
        };
      });
    setSections(newSections);
    setMeta((p) => ({ ...p, targetScore: autoConfig.totalScore, duration: autoConfig.duration }));
    setAutoGeneratedBanner(true);
    setActiveTab('manual');
    toast.success(`已自动生成试卷，共 ${newSections.reduce((s, x) => s + x.questions.length, 0)} 道题目`);
  };

  // ── save ──
  const handleSave = () => {
    if (!meta.title.trim()) { toast.error('请填写试卷名称'); return; }
    if (totalQuestions === 0) { toast.error('请先添加题目'); return; }
    toast.success('试卷已保存为草稿，即将跳转到考试管理');
    setTimeout(() => router.push('/teacher/exams'), 1200);
  };

  // ── render ──
  return (
    <div className="p-6 space-y-4">
      <h1 className="text-xl font-bold text-gray-900">智能组卷</h1>

      {/* ── Paper meta bar ── */}
      <Card className="shadow-none border">
        <CardContent className="p-4 space-y-3">
          <div className="grid grid-cols-3 gap-4">
            <div className="col-span-2 space-y-1">
              <Label className="text-xs">试卷名称 <span className="text-red-500">*</span></Label>
              <Input
                placeholder="请输入试卷名称，如：2024-2025第二学期 数据结构 期末考试"
                value={meta.title}
                onChange={(e) => setMeta((p) => ({ ...p, title: e.target.value }))}
                className="h-8 text-sm"
              />
            </div>
            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-1">
                <Label className="text-xs">考试时长</Label>
                <Select value={String(meta.duration)} onValueChange={(v) => setMeta((p) => ({ ...p, duration: Number(v) }))}>
                  <SelectTrigger className="h-8 text-sm">
                    <SelectValue>{meta.duration} 分钟</SelectValue>
                  </SelectTrigger>
                  <SelectContent>
                    {DURATIONS.map((d) => <SelectItem key={d} value={String(d)}>{d} 分钟</SelectItem>)}
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-1">
                <Label className="text-xs">目标总分</Label>
                <div className="flex items-center gap-1">
                  <Input type="number" value={meta.targetScore} min={1}
                    onChange={(e) => setMeta((p) => ({ ...p, targetScore: Number(e.target.value) }))}
                    className="h-8 text-sm flex-1" />
                  <span className="text-xs text-muted-foreground">分</span>
                </div>
              </div>
            </div>
          </div>
          <div className="space-y-1">
            <Label className="text-xs">考试须知（选填，将展示在学生端试卷顶部）</Label>
            <Textarea
              placeholder="如：不允许使用计算器，禁止携带手机，独立完成..."
              value={meta.instructions}
              onChange={(e) => setMeta((p) => ({ ...p, instructions: e.target.value }))}
              rows={2} className="text-sm resize-none"
            />
          </div>
        </CardContent>
      </Card>

      {/* ── Tabs ── */}
      <Tabs value={activeTab} onValueChange={(v) => setActiveTab(v as 'manual' | 'auto')}>
        <TabsList>
          <TabsTrigger value="manual">手动组卷</TabsTrigger>
          <TabsTrigger value="auto">自动组卷</TabsTrigger>
        </TabsList>

        {/* ══ MANUAL ══════════════════════════════════════════════════════ */}
        <TabsContent value="manual" className="mt-4">
          {autoGeneratedBanner && (
            <div className="flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm mb-3 border"
              style={{ background: '#ecfdf5', borderColor: '#6ee7b7', color: '#065f46' }}>
              <CheckCircle2 size={15} />
              已自动生成试卷，你可以在下方调整题目和顺序。
              <button className="ml-auto" onClick={() => setAutoGeneratedBanner(false)}><X size={14} /></button>
            </div>
          )}
          <div className="grid grid-cols-5 gap-4">
            {/* Left: question pool */}
            <div className="col-span-2 space-y-3">
              {/* Filters */}
              <Card className="shadow-none border">
                <CardContent className="p-3 space-y-2">
                  <div className="relative">
                    <Search size={13} className="absolute left-2.5 top-1/2 -translate-y-1/2 text-muted-foreground" />
                    <Input placeholder="搜索题目..." value={searchText}
                      onChange={(e) => setSearchText(e.target.value)}
                      className="h-7 text-xs pl-8" />
                  </div>
                  <div className="grid grid-cols-3 gap-1.5">
                    <div className="space-y-0.5">
                      <p className="text-xs text-muted-foreground">学科</p>
                      <Select value={subjectFilter} onValueChange={(v) => setSubjectFilter(v ?? 'all')}>
                        <SelectTrigger className="h-7 text-xs">
                          <SelectValue>{subjectFilter === 'all' ? '全部' : subjectFilter}</SelectValue>
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="all">全部学科</SelectItem>
                          {subjects.map((s) => <SelectItem key={s} value={s}>{s}</SelectItem>)}
                        </SelectContent>
                      </Select>
                    </div>
                    <div className="space-y-0.5">
                      <p className="text-xs text-muted-foreground">难度</p>
                      <Select value={diffFilter} onValueChange={(v) => setDiffFilter(v ?? 'all')}>
                        <SelectTrigger className="h-7 text-xs">
                          <SelectValue>{diffFilter === 'all' ? '全部' : diffLabels[diffFilter as Difficulty]}</SelectValue>
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="all">全部难度</SelectItem>
                          {(Object.entries(diffLabels) as [Difficulty, string][]).map(([v, l]) => (
                            <SelectItem key={v} value={v}>{l}</SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                    </div>
                    <div className="space-y-0.5">
                      <p className="text-xs text-muted-foreground">题型</p>
                      <Select value={typeFilter} onValueChange={(v) => setTypeFilter(v ?? 'all')}>
                        <SelectTrigger className="h-7 text-xs">
                          <SelectValue>{typeFilter === 'all' ? '全部' : typeLabels[typeFilter as QuestionType]}</SelectValue>
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="all">全部题型</SelectItem>
                          {(Object.entries(typeLabels) as [QuestionType, string][]).map(([v, l]) => (
                            <SelectItem key={v} value={v}>{l}</SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                    </div>
                  </div>
                  <p className="text-xs text-muted-foreground">题库 {filteredPool.length} / {pool.length} 题</p>
                </CardContent>
              </Card>

              {/* Question list */}
              <Card className="shadow-none border">
                <CardContent className="p-0 max-h-[520px] overflow-y-auto">
                  {filteredPool.length === 0 && (
                    <p className="text-xs text-muted-foreground p-4 text-center">无匹配题目</p>
                  )}
                  {filteredPool.map((q) => {
                    const inPaper = allSectionQIds.includes(q.id);
                    return (
                      <div
                        key={q.id}
                        className={`flex items-start gap-2.5 px-3 py-2.5 border-b last:border-0 transition-colors ${inPaper ? 'bg-blue-50/60' : 'hover:bg-muted/30 cursor-pointer'}`}
                        onClick={() => !inPaper && addToSection(q)}
                      >
                        <div className={`w-3.5 h-3.5 rounded border-2 mt-0.5 flex-shrink-0 flex items-center justify-center ${inPaper ? 'border-blue-500 bg-blue-500' : 'border-gray-300'}`}>
                          {inPaper && <svg width="8" height="6" viewBox="0 0 10 8" fill="none"><path d="M1 4l2.5 2.5L9 1" stroke="white" strokeWidth="2.5" strokeLinecap="round" /></svg>}
                        </div>
                        <div className="flex-1 min-w-0">
                          <p className="text-xs text-gray-800 line-clamp-2 leading-relaxed">{q.content}</p>
                          <div className="flex items-center gap-1.5 mt-1 flex-wrap">
                            <span className={`text-xs px-1.5 py-0.5 rounded-full font-medium ${diffColors[q.difficulty]}`}>{diffLabels[q.difficulty]}</span>
                            <Badge variant="secondary" className="text-xs h-4 px-1">{typeLabels[q.type]}</Badge>
                            <span className="text-xs text-muted-foreground">{q.score}分</span>
                          </div>
                        </div>
                        {!inPaper && <Plus size={14} className="text-muted-foreground mt-0.5 flex-shrink-0" />}
                      </div>
                    );
                  })}
                </CardContent>
              </Card>
            </div>

            {/* Right: sections */}
            <div className="col-span-3 space-y-3">
              {sections.map((s, si) => {
                const sectionScore = s.questions.reduce((sum, sq) => sum + sq.score, 0);
                const scoreWarning = sectionScore > s.targetScore;
                return (
                  <Card key={s.id} className="shadow-none border">
                    {/* Section header */}
                    <div className="flex items-center gap-2 px-4 py-2.5 border-b bg-muted/20">
                      <span className="text-sm font-semibold text-gray-800">
                        {CHINESE_NUM[si] ?? si + 1}、{s.name}
                      </span>
                      <span className={`text-xs font-medium ${scoreWarning ? 'text-yellow-600' : 'text-muted-foreground'}`}>
                        （{scoreWarning && '⚠ '}目标{s.targetScore}分，当前{sectionScore}分）
                      </span>
                      <div className="ml-auto flex items-center gap-1">
                        <button
                          className="text-xs text-blue-600 hover:underline px-1"
                          onClick={() => setEditSectionScore({ id: s.id, val: String(s.targetScore) })}
                        >调整分值</button>
                        <button
                          className="p-1 rounded hover:bg-muted text-muted-foreground"
                          onClick={() => toggleCollapse(s.id)}
                          title={s.collapsed ? '展开' : '收起'}
                        >
                          {s.collapsed ? <ChevronDown size={14} /> : <ChevronUp size={14} />}
                        </button>
                        <button
                          className="p-1 rounded hover:bg-muted text-red-400"
                          onClick={() => setDeleteSectionTarget(s)}
                          title="删除大题"
                        >
                          <Trash2 size={13} />
                        </button>
                      </div>
                    </div>

                    {/* Section body */}
                    {!s.collapsed && (
                      <CardContent className="p-0">
                        {s.questions.length === 0 ? (
                          <p className="text-xs text-muted-foreground p-4 text-center">
                            暂无题目，从左侧题库点击添加
                          </p>
                        ) : (
                          s.questions.map((sq, qi) => {
                            const q = getQById(sq.qId);
                            if (!q) return null;
                            const isEditingScore = inlineScoreEdit?.sid === s.id && inlineScoreEdit?.qid === sq.qId;
                            return (
                              <div
                                key={sq.qId}
                                draggable
                                onDragStart={() => setDragItem({ sid: s.id, qi })}
                                onDragOver={(e) => { e.preventDefault(); setDragOver({ sid: s.id, qi }); }}
                                onDrop={() => {
                                  if (!dragItem || dragItem.sid !== s.id || dragItem.qi === qi) {
                                    setDragItem(null); setDragOver(null); return;
                                  }
                                  setSections((prev) => prev.map((sec) => {
                                    if (sec.id !== s.id) return sec;
                                    const qs = [...sec.questions];
                                    const [moved] = qs.splice(dragItem.qi, 1);
                                    qs.splice(qi, 0, moved);
                                    return { ...sec, questions: qs };
                                  }));
                                  setDragItem(null); setDragOver(null);
                                }}
                                onDragEnd={() => { setDragItem(null); setDragOver(null); }}
                                className={`flex items-center gap-2 px-4 py-2.5 border-b last:border-0 group transition-colors ${
                                  dragOver?.sid === s.id && dragOver?.qi === qi && dragItem?.qi !== qi
                                    ? 'bg-blue-50 border-t-2 border-t-blue-400'
                                    : dragItem?.sid === s.id && dragItem?.qi === qi
                                    ? 'opacity-40'
                                    : ''
                                }`}
                              >
                                <span className="text-muted-foreground opacity-0 group-hover:opacity-100 cursor-grab active:cursor-grabbing flex-shrink-0 transition-opacity">
                                  <GripVertical size={14} />
                                </span>
                                <span className="text-xs text-muted-foreground w-5 flex-shrink-0">{qi + 1}.</span>
                                <p className="text-xs flex-1 truncate text-gray-800">{q.content}</p>
                                {/* inline score */}
                                {isEditingScore ? (
                                  <input
                                    autoFocus
                                    type="number"
                                    defaultValue={sq.score}
                                    className="w-12 h-6 border rounded text-xs text-center px-1 focus:outline-none focus:ring-1 focus:ring-blue-400"
                                    onBlur={(e) => {
                                      updateQuestionScore(s.id, sq.qId, Number(e.target.value) || sq.score);
                                      setInlineScoreEdit(null);
                                    }}
                                    onKeyDown={(e) => {
                                      if (e.key === 'Enter') (e.target as HTMLInputElement).blur();
                                      if (e.key === 'Escape') setInlineScoreEdit(null);
                                    }}
                                  />
                                ) : (
                                  <button
                                    className="text-xs text-muted-foreground hover:text-blue-600 hover:underline w-10 text-right flex-shrink-0"
                                    title="点击修改分值"
                                    onClick={() => setInlineScoreEdit({ sid: s.id, qid: sq.qId, val: String(sq.score) })}
                                  >
                                    {sq.score}分
                                  </button>
                                )}
                                <button onClick={() => removeFromSection(s.id, sq.qId)}
                                  className="p-1 opacity-0 group-hover:opacity-100 text-red-400 hover:text-red-600 transition-opacity">
                                  <Trash2 size={13} />
                                </button>
                              </div>
                            );
                          })
                        )}
                        {s.questions.length > 0 && (
                          <div className="px-4 py-2 bg-muted/10 text-xs text-muted-foreground">
                            小计：{s.questions.length} 题 / {sectionScore} 分
                          </div>
                        )}
                      </CardContent>
                    )}
                  </Card>
                );
              })}

              {/* Add section */}
              <button
                onClick={() => setAddSectionOpen(true)}
                className="w-full flex items-center justify-center gap-1.5 py-2.5 rounded-lg border border-dashed border-gray-200 text-xs text-muted-foreground hover:bg-muted/30 transition-colors"
              >
                <Plus size={13} /> 新增大题
              </button>

              {/* Status bar */}
              <Card className="shadow-none border">
                <CardContent className="p-3 space-y-2">
                  <div className="flex items-center gap-4 text-xs">
                    <span className="text-muted-foreground">题目数量：<span className="font-semibold text-gray-800">{totalQuestions} 题</span></span>
                    <span className="text-muted-foreground">当前总分：
                      <span className={`font-semibold ${scoreDiff === 0 ? 'text-green-600' : 'text-yellow-600'}`}>
                        {currentScore}
                      </span>
                      <span className="text-muted-foreground"> / {meta.targetScore} 分</span>
                    </span>
                  </div>
                  {scoreDiff < 0 && (
                    <div className="flex items-center gap-1.5 text-xs text-yellow-700">
                      <AlertTriangle size={12} /> 总分未达目标，还差 {Math.abs(scoreDiff)} 分
                    </div>
                  )}
                  {scoreDiff > 0 && (
                    <div className="flex items-center gap-1.5 text-xs text-yellow-700">
                      <AlertTriangle size={12} /> 总分超出目标 {scoreDiff} 分
                    </div>
                  )}
                  {scoreDiff === 0 && totalQuestions > 0 && (
                    <div className="flex items-center gap-1.5 text-xs text-green-700">
                      <CheckCircle2 size={12} /> 总分匹配
                    </div>
                  )}
                  <div className="flex gap-2 pt-1">
                    <Button variant="outline" className="flex-1 gap-1.5" onClick={() => setPreviewOpen(true)} disabled={totalQuestions === 0}>
                      <Eye size={14} /> 预览试卷
                    </Button>
                    <Button className="flex-1 text-white" style={{ background: '#002045' }} onClick={handleSave}>
                      保存试卷
                    </Button>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </TabsContent>

        {/* ══ AUTO ════════════════════════════════════════════════════════ */}
        <TabsContent value="auto" className="mt-4">
          <div className="grid grid-cols-5 gap-4">
            {/* Config form */}
            <div className="col-span-3 space-y-4">
              <Card className="shadow-none border">
                <CardHeader className="pb-2">
                  <CardTitle className="text-sm">基本设置</CardTitle>
                </CardHeader>
                <CardContent className="grid grid-cols-3 gap-3">
                  <div className="space-y-1">
                    <Label className="text-xs">学科</Label>
                    <Select value={autoConfig.subject} onValueChange={(v) => setAutoConfig((p) => ({ ...p, subject: v ?? p.subject }))}>
                      <SelectTrigger className="h-8 text-sm"><SelectValue>{autoConfig.subject}</SelectValue></SelectTrigger>
                      <SelectContent>
                        {subjects.map((s) => <SelectItem key={s} value={s}>{s}</SelectItem>)}
                      </SelectContent>
                    </Select>
                  </div>
                  <div className="space-y-1">
                    <Label className="text-xs">目标总分</Label>
                    <div className="flex items-center gap-1">
                      <Input type="number" value={autoConfig.totalScore} className="h-8 text-sm"
                        onChange={(e) => setAutoConfig((p) => ({ ...p, totalScore: Number(e.target.value) }))} />
                      <span className="text-xs text-muted-foreground">分</span>
                    </div>
                  </div>
                  <div className="space-y-1">
                    <Label className="text-xs">考试时长</Label>
                    <Select value={String(autoConfig.duration)} onValueChange={(v) => setAutoConfig((p) => ({ ...p, duration: Number(v) }))}>
                      <SelectTrigger className="h-8 text-sm"><SelectValue>{autoConfig.duration} 分钟</SelectValue></SelectTrigger>
                      <SelectContent>
                        {DURATIONS.map((d) => <SelectItem key={d} value={String(d)}>{d} 分钟</SelectItem>)}
                      </SelectContent>
                    </Select>
                  </div>
                </CardContent>
              </Card>

              {/* Type config table */}
              <Card className="shadow-none border">
                <CardHeader className="pb-2">
                  <CardTitle className="text-sm">题型配置</CardTitle>
                </CardHeader>
                <CardContent className="p-0">
                  <table className="w-full text-sm">
                    <thead>
                      <tr className="border-b bg-muted/30">
                        <th className="text-left py-2 px-4 text-xs text-muted-foreground font-medium">题型</th>
                        <th className="text-center py-2 px-2 text-xs text-muted-foreground font-medium">题数</th>
                        <th className="text-center py-2 px-2 text-xs text-muted-foreground font-medium">每题分值</th>
                        <th className="text-center py-2 px-2 text-xs text-muted-foreground font-medium">小计</th>
                        <th className="text-center py-2 px-2 text-xs text-muted-foreground font-medium">难度分布</th>
                      </tr>
                    </thead>
                    <tbody>
                      {(Object.entries(autoTypes) as [QuestionType, AutoTypeConfig][]).map(([type, cfg]) => {
                        const subtotal = cfg.count * cfg.scoreEach;
                        const isExpanded = diffExpandFor === type;
                        const diffSum = cfg.diff.easy + cfg.diff.medium + cfg.diff.hard;
                        const diffOk = diffSum === 100;
                        return (
                          <>
                            <tr key={type} className="border-b">
                              <td className="py-2.5 px-4 font-medium text-xs">{typeLabels[type]}</td>
                              <td className="py-2 px-2 text-center">
                                <input type="number" min={0} value={cfg.count}
                                  onChange={(e) => setAutoTypes((p) => ({ ...p, [type]: { ...p[type], count: Number(e.target.value) } }))}
                                  className="w-12 h-6 border rounded text-xs text-center px-1 focus:outline-none focus:ring-1 focus:ring-blue-400" />
                              </td>
                              <td className="py-2 px-2 text-center">
                                <input type="number" min={1} value={cfg.scoreEach}
                                  onChange={(e) => setAutoTypes((p) => ({ ...p, [type]: { ...p[type], scoreEach: Number(e.target.value) } }))}
                                  className="w-12 h-6 border rounded text-xs text-center px-1 focus:outline-none focus:ring-1 focus:ring-blue-400" />
                              </td>
                              <td className="py-2.5 px-2 text-center text-xs font-semibold">{subtotal}分</td>
                              <td className="py-2 px-2 text-center">
                                <button
                                  className={`text-xs px-2 py-0.5 rounded ${isExpanded ? 'text-blue-700 bg-blue-50' : 'text-blue-600 hover:bg-muted'}`}
                                  onClick={() => setDiffExpandFor(isExpanded ? null : type)}
                                >
                                  {isExpanded ? '收起 ▲' : '配置 →'}
                                </button>
                              </td>
                            </tr>
                            {isExpanded && (
                              <tr key={`${type}-diff`} className="border-b bg-muted/10">
                                <td colSpan={5} className="px-4 py-3">
                                  <div className="flex items-center gap-4 text-xs">
                                    {(['easy', 'medium', 'hard'] as Difficulty[]).map((d) => (
                                      <label key={d} className="flex items-center gap-1.5">
                                        <span className={`px-1.5 py-0.5 rounded-full text-xs font-medium ${diffColors[d]}`}>{diffLabels[d]}</span>
                                        <input type="number" min={0} max={100} value={cfg.diff[d]}
                                          onChange={(e) => setAutoTypes((p) => ({ ...p, [type]: { ...p[type], diff: { ...p[type].diff, [d]: Number(e.target.value) } } }))}
                                          className={`w-14 h-6 border rounded text-xs text-center px-1 focus:outline-none focus:ring-1 ${diffOk ? 'focus:ring-blue-400' : 'border-red-300 focus:ring-red-400'}`} />
                                        <span>%</span>
                                      </label>
                                    ))}
                                    <span className={`ml-auto text-xs font-medium ${diffOk ? 'text-green-600' : 'text-red-500'}`}>
                                      合计：{diffSum}% {diffOk ? '✓' : '⚠ 须等于100%'}
                                    </span>
                                  </div>
                                </td>
                              </tr>
                            )}
                          </>
                        );
                      })}
                      <tr className="border-t bg-muted/20">
                        <td className="py-2 px-4 text-xs font-semibold">合计</td>
                        <td className="py-2 px-2 text-center text-xs font-semibold">
                          {(Object.values(autoTypes) as AutoTypeConfig[]).reduce((s, c) => s + c.count, 0)} 题
                        </td>
                        <td />
                        <td className="py-2 px-2 text-center text-xs font-bold" style={{ color: '#002045' }}>
                          {autoTotalScore} 分
                        </td>
                        <td />
                      </tr>
                    </tbody>
                  </table>
                </CardContent>
              </Card>

              {/* Advanced options */}
              <Card className="shadow-none border">
                <CardHeader className="pb-2">
                  <CardTitle className="text-sm">高级选项</CardTitle>
                </CardHeader>
                <CardContent className="space-y-2">
                  <label className="flex items-center gap-2 text-sm cursor-pointer">
                    <input type="checkbox" checked={autoConfig.excludeRecent}
                      onChange={(e) => setAutoConfig((p) => ({ ...p, excludeRecent: e.target.checked }))}
                      className="rounded" />
                    排除近 30 天内使用过的题目
                  </label>
                  <div className="flex items-center gap-2 text-sm">
                    <input type="checkbox" className="rounded" defaultChecked />
                    <span>同一章节最多</span>
                    <input type="number" min={1} value={autoConfig.sameChapterMax}
                      onChange={(e) => setAutoConfig((p) => ({ ...p, sameChapterMax: Number(e.target.value) }))}
                      className="w-12 h-6 border rounded text-xs text-center px-1" />
                    <span>题</span>
                  </div>
                </CardContent>
              </Card>
            </div>

            {/* Library check + generate */}
            <div className="col-span-2 space-y-4">
              <Card className="shadow-none border">
                <CardHeader className="pb-2">
                  <CardTitle className="text-sm">题库匹配情况</CardTitle>
                </CardHeader>
                <CardContent className="space-y-2">
                  {(Object.entries(autoTypes) as [QuestionType, AutoTypeConfig][]).map(([type, cfg]) => {
                    if (cfg.count === 0) return null;
                    const available = pool.filter((q) => q.type === type && (autoConfig.subject === 'all' || q.subject === autoConfig.subject)).length;
                    const status = autoLibCheck(type);
                    return (
                      <div key={type} className="flex items-center gap-2 text-xs">
                        {status === 'ok' && <CheckCircle2 size={14} className="text-green-600 flex-shrink-0" />}
                        {status === 'warn' && <AlertTriangle size={14} className="text-yellow-500 flex-shrink-0" />}
                        {status === 'error' && <XCircle size={14} className="text-red-500 flex-shrink-0" />}
                        <span>
                          <span className="font-medium">{typeLabels[type]}：</span>
                          题库 {available} 题，需 {cfg.count} 题，
                          <span className={status === 'ok' ? 'text-green-700' : status === 'warn' ? 'text-yellow-700' : 'text-red-600'}>
                            {status === 'ok' ? '充足' : status === 'warn' ? '勉强' : '不足'}
                          </span>
                        </span>
                      </div>
                    );
                  })}
                  {!canGenerate && (
                    <p className="text-xs text-red-500 mt-1">
                      ⚠ 题库不足，请先录入更多题目或调整题数配置
                    </p>
                  )}
                </CardContent>
              </Card>

              <Card className="shadow-none border">
                <CardContent className="p-4 space-y-2">
                  <div className="text-xs text-muted-foreground space-y-1">
                    <div className="flex justify-between"><span>配置总分</span><span className={autoTotalScore === autoConfig.totalScore ? 'text-green-600 font-semibold' : 'text-yellow-600 font-semibold'}>{autoTotalScore}分 / {autoConfig.totalScore}分</span></div>
                    {autoTotalScore !== autoConfig.totalScore && (
                      <p className="text-yellow-600">配置分值与目标总分不一致</p>
                    )}
                  </div>
                  <Button
                    className="w-full gap-1.5 text-white"
                    style={{ background: canGenerate ? '#006c4a' : '#9ca3af' }}
                    disabled={!canGenerate}
                    onClick={handleGenerate}
                  >
                    <Wand2 size={15} />
                    生成试卷
                  </Button>
                </CardContent>
              </Card>
            </div>
          </div>
        </TabsContent>
      </Tabs>

      {/* ── Add section dialog ── */}
      <Dialog open={addSectionOpen} onOpenChange={setAddSectionOpen}>
        <DialogContent className="max-w-xs">
          <DialogHeader><DialogTitle>新增大题</DialogTitle></DialogHeader>
          <div className="space-y-3">
            <div className="space-y-1">
              <Label className="text-xs">大题名称</Label>
              <Input placeholder="如：综合应用题" value={newSectionName}
                onChange={(e) => setNewSectionName(e.target.value)}
                className="h-8 text-sm" />
            </div>
            <div className="space-y-1">
              <Label className="text-xs">目标总分</Label>
              <div className="flex items-center gap-1">
                <Input type="number" value={newSectionScore}
                  onChange={(e) => setNewSectionScore(Number(e.target.value))}
                  className="h-8 text-sm" />
                <span className="text-xs text-muted-foreground">分</span>
              </div>
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setAddSectionOpen(false)}>取消</Button>
            <Button className="text-white" style={{ background: '#002045' }} onClick={addSection}>确认添加</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* ── Edit section target score ── */}
      <Dialog open={!!editSectionScore} onOpenChange={(o) => !o && setEditSectionScore(null)}>
        <DialogContent className="max-w-xs">
          <DialogHeader><DialogTitle>调整大题目标分值</DialogTitle></DialogHeader>
          <div className="space-y-1">
            <Label className="text-xs">目标总分</Label>
            <div className="flex items-center gap-1">
              <Input type="number" value={editSectionScore?.val ?? ''}
                onChange={(e) => setEditSectionScore((p) => p ? { ...p, val: e.target.value } : null)}
                className="h-8 text-sm" autoFocus />
              <span className="text-xs text-muted-foreground">分</span>
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setEditSectionScore(null)}>取消</Button>
            <Button className="text-white" style={{ background: '#002045' }} onClick={() => {
              if (!editSectionScore) return;
              setSections((prev) => prev.map((s) => s.id === editSectionScore.id ? { ...s, targetScore: Number(editSectionScore.val) || s.targetScore } : s));
              setEditSectionScore(null);
              toast.success('分值已更新');
            }}>确认</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* ── Delete section confirm ── */}
      <Dialog open={!!deleteSectionTarget} onOpenChange={(o) => !o && setDeleteSectionTarget(null)}>
        <DialogContent className="max-w-sm">
          <DialogHeader><DialogTitle>确认删除大题</DialogTitle></DialogHeader>
          <p className="text-sm text-muted-foreground">
            大题「{deleteSectionTarget?.name}」下有 {deleteSectionTarget?.questions.length} 道题目，删除后题目将回到左侧题库，确认删除？
          </p>
          <DialogFooter>
            <Button variant="outline" onClick={() => setDeleteSectionTarget(null)}>取消</Button>
            <Button variant="destructive" onClick={() => deleteSectionTarget && confirmDeleteSection(deleteSectionTarget)}>确认删除</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* ── Preview dialog ── */}
      <Dialog open={previewOpen} onOpenChange={setPreviewOpen}>
        <DialogContent className="max-w-3xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>试卷预览（学生视角）</DialogTitle>
          </DialogHeader>
          <div className="bg-white rounded border p-8 space-y-6 text-sm">
            <div className="text-center space-y-1">
              <h2 className="text-xl font-bold text-gray-900">{meta.title || '（未填写试卷名称）'}</h2>
              <p className="text-sm text-muted-foreground">
                考试时长：{meta.duration} 分钟 &nbsp;|&nbsp; 总分：{meta.targetScore} 分
              </p>
              {meta.instructions && (
                <p className="text-xs text-gray-600 border border-dashed border-gray-200 rounded px-3 py-2 inline-block mt-1">
                  考试须知：{meta.instructions}
                </p>
              )}
            </div>
            <hr />
            {sections.filter((s) => s.questions.length > 0).map((s, si) => {
              const sScore = s.questions.reduce((sum, sq) => sum + sq.score, 0);
              const perScore = s.questions.length > 0 ? s.questions[0].score : 0;
              const allSameScore = s.questions.every((sq) => sq.score === perScore);
              return (
                <div key={s.id} className="space-y-4">
                  <h3 className="font-bold text-base">
                    {CHINESE_NUM[si] ?? si + 1}、{s.name}
                    （{allSameScore ? `每题 ${perScore} 分，` : ''}共 {sScore} 分）
                  </h3>
                  {s.questions.map((sq, qi) => {
                    const q = getQById(sq.qId);
                    if (!q) return null;
                    return (
                      <div key={sq.qId} className="space-y-2">
                        <p className="font-medium">{qi + 1}. {q.content}</p>
                        {q.type === 'choice' && q.options && (
                          <div className="grid grid-cols-2 gap-1 pl-4">
                            {q.options.map((opt) => (
                              <p key={opt} className="text-sm text-gray-700">{opt}</p>
                            ))}
                          </div>
                        )}
                        {q.type === 'fill' && (
                          <div className="pl-4">
                            <div className="inline-block w-32 border-b-2 border-gray-400 h-5" />
                          </div>
                        )}
                        {(q.type === 'short' || q.type === 'essay') && (
                          <div className="pl-4 space-y-1">
                            {Array.from({ length: q.type === 'essay' ? 6 : 3 }).map((_, i) => (
                              <div key={i} className="h-6 border-b border-gray-200" />
                            ))}
                          </div>
                        )}
                      </div>
                    );
                  })}
                </div>
              );
            })}
            {sections.every((s) => s.questions.length === 0) && (
              <p className="text-center text-muted-foreground py-8">试卷暂无题目</p>
            )}
          </div>
          <DialogFooter className="gap-2">
            <Button variant="outline" onClick={() => setPreviewOpen(false)}>关闭预览</Button>
            <Button variant="outline" onClick={() => { toast.success('PDF 导出功能开发中'); }}>导出 PDF</Button>
            <Button className="text-white gap-1" style={{ background: '#002045' }}
              onClick={() => { setPreviewOpen(false); handleSave(); }}>
              发布考试 <ChevronRight size={14} />
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
